# Generated by Django 3.2.4 on 2021-06-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('baho', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=3, verbose_name='sinfi')),
            ],
            options={
                'verbose_name': 'sinf',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, null=True, verbose_name='ism')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='familya')),
                ('age', models.DateField(verbose_name='yosh')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('time', models.DateField(auto_now_add=True, null=True, verbose_name='vaxt')),
                ('gradue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urok.classroom', verbose_name='sinfi')),
            ],
            options={
                'verbose_name': "o'quvchi",
                'verbose_name_plural': "o'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='fan nomi')),
                ('sinflar', models.ManyToManyField(through='urok.Baho', to='urok.Pupil')),
            ],
        ),
        migrations.AddField(
            model_name='baho',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urok.lesson'),
        ),
        migrations.AddField(
            model_name='baho',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urok.pupil'),
        ),
        migrations.AddField(
            model_name='baho',
            name='sinf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urok.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='baho',
            unique_together={('name', 'lesson', 'sinf')},
        ),
    ]
