# Generated by Django 2.2.12 on 2021-06-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=3, verbose_name='sinfi')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, null=True, verbose_name='ism')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='familya')),
                ('age', models.CharField(max_length=30, verbose_name='yosh')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('gradue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urok.Classroom', verbose_name='sinfi')),
            ],
            options={
                'verbose_name': "o'quvchi",
                'verbose_name_plural': "o'quvchilar",
            },
        ),
    ]
