# Generated by Django 2.2.12 on 2021-06-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'sinf', 'verbose_name_plural': 'sinflar'},
        ),
    ]
