# Generated by Django 3.2.4 on 2021-06-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0002_classroom_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='fan',
        ),
        migrations.AddField(
            model_name='classroom',
            name='fan',
            field=models.ManyToManyField(to='urok.Lesson', verbose_name='fan'),
        ),
    ]
