# Generated by Django 2.2.12 on 2021-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0002_auto_20210618_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='vaxt'),
        ),
    ]
