# Generated by Django 3.2.4 on 2021-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0003_auto_20210620_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='gradue',
        ),
        migrations.AddField(
            model_name='pupil',
            name='gradue',
            field=models.ManyToManyField(to='urok.Classroom', verbose_name='sinfi'),
        ),
    ]
