# Generated by Django 2.2.12 on 2021-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0003_pupil_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='time',
            field=models.DateField(null=True, verbose_name='vaxt'),
        ),
    ]
