# Generated by Django 3.2.4 on 2021-06-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0004_auto_20210620_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='gradue',
        ),
        migrations.AddField(
            model_name='pupil',
            name='gradue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urok.classroom', verbose_name='sinfi'),
        ),
    ]
