# Generated by Django 3.2.4 on 2021-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0005_auto_20210620_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='vaxt'),
        ),
    ]
