# Generated by Django 3.2.4 on 2021-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0005_auto_20210620_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='pupils',
            field=models.ManyToManyField(to='urok.Pupil'),
        ),
    ]
