# Generated by Django 3.2.4 on 2021-06-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0006_classroom_pupils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='pupils',
        ),
    ]
