# Generated by Django 3.2.4 on 2021-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0006_alter_pupil_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='age',
            field=models.DateField(verbose_name='yosh'),
        ),
    ]
