# Generated by Django 3.2.4 on 2021-06-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0007_remove_classroom_pupils'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baho',
            unique_together={('name', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='baho',
            name='sinf',
        ),
    ]
