# Generated by Django 3.2.4 on 2021-06-20 21:59

from django.db import migrations
import urok.models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0008_auto_20210620_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baho',
            name='baho',
            field=urok.models.IntegerRangeField(null=True),
        ),
    ]
