# Generated by Django 3.2.4 on 2021-06-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urok', '0009_alter_baho_baho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baho',
            name='baho',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
